Repository GuillermoEchague/frontend-project, pull requests merged in 2024-12, with the labels that each got.

#2 Feat (API) : Fix JsDocs api
  package-lock.json
  package.json
  src/App.jsx
  src/api/Service.js
  src/constants/Constants.js
  src/error/APIErrors.js
Labels: enhancement

#10 Add component main card
  src/App.css
  src/App.jsx
  src/components/Card/Card.css
  src/components/Card/Card.jsx
  src/components/ContainerCard.css
  src/components/ContainerCard.jsx
  src/index.css
  src/main.jsx
Labels: bug

#12 Add component main card
  package-lock.json
  package.json
  src/App.jsx
  src/assets/img/logoanime.png
  src/assets/react.svg
  src/components/Card/Card.jsx
  src/components/Card/Card.scss
  src/components/ContainerCard/ContainerCard.jsx
  src/components/ContainerCard/ContainerCard.scss
  src/components/Filtros/Filtros.jsx
  src/components/Filtros/Filtros.scss
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.scss
  src/main.scss
  vite.config.js
Labels: enhancement

#14 Add Navbar
  src/App.jsx
  src/components/ContainerCard.css
  src/components/ContainerCard.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/Navbar.scss
  src/components/Navbar/index.js
Labels: enhancement

#16 Feature/mejoras estilos y componentes
  package-lock.json
  package.json
  src/App.jsx
  src/components/Card/Card.css
  src/components/Card/Card.scss
  src/components/ContainerCard/ContainerCard.scss
  src/components/Filtros/Filtros.jsx
  src/components/Filtros/Filtros.scss
  src/components/Footer/Footer.scss
  src/main.jsx
  src/main.scss
  src/screens/Home.jsx
  src/variables.scss
  vite.config.js
Labels: wontfix
